groups:
  - name: sp500_alerts
    rules:
      - alert: APIHighLatency
        expr: rate(prediction_latency_seconds_sum[1m]) / rate(prediction_latency_seconds_count[1m]) > 0.1
        for: 1m
        annotations:
          summary: "API latency is high"
          
      - alert: APIDown
        expr: up{job="sp500-api"} == 0
        for: 30s
        annotations:
          summary: "API is down"
          
      - alert: HighPredictionErrorRate
        expr: rate(predictions_total[5m]) < 10
        for: 5m
        annotations:
          summary: "Low prediction throughput"
