apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sp500-model-pvc
  namespace: default
  labels:
    app: sp500-predictor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard