apiVersion: v1
kind: Service
metadata:
  name: sp500-predictor-api
  namespace: default
  labels:
    app: sp500-predictor
    component: api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8000
    protocol: TCP
    name: https
  selector:
    app: sp500-predictor
    component: api
  sessionAffinity: None